# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d8d528678a8ce1288bbe7bc34d4ac09c3d31635aa3b75f16ec1851b8dfe292b76bacd71f61e632cc69b34cd95fc94318d2a21aefed2021d79bcdc91889756a

test:
  secret_key_base: d960ece48e0ed2d295c2ace7b72a87d609d5358992bf3602306fd07889d2aa2b24c194c23659659f8f042ae86134b31e18eba2c974851b7ecfe95d86e156ed6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
